import { useMemo,useState } from "react";
import { AppShell } from "../../components/AppShell";
import { Button } from "../../components/Button";
import { Card } from "../../components/Card";
import { FeedbackBox } from "../../components/FeedbackBox";
import { ProgressBar } from "../../components/ProgressBar";
import { finalTestTasks,isExactAnswer,scoreTest,transferTasks,type Phase5Task } from "../../data/phase5";
import { shuffle } from "../../utils/shuffle";

type Stage="transfer"|"transition"|"test"|"result";
const decorations=[{asset:"bookStack",position:"bottom-left",size:"clamp(10rem,20vw,18rem)",opacity:.15,visibility:"tablet-up"},{asset:"seal",position:"bottom-right",size:"clamp(9rem,18vw,16rem)",opacity:.2,visibility:"desktop"}] as const;
const answerText=(answers:readonly string[])=>answers.length?answers.join(" · "):"Keine Antwort";

function Options({task,selected,locked,onToggle}:{task:Phase5Task;selected:readonly string[];locked:boolean;onToggle:(option:string)=>void}){const options=useMemo(()=>shuffle(task.options),[task]);return <div className="feature-card-grid phase5-options">{options.map(option=><button type="button" key={option} className={`feature-choice ${selected.includes(option)?"feature-choice--selected":""}`} aria-pressed={selected.includes(option)} disabled={locked} onClick={()=>onToggle(option)}><span>{option}</span></button>)}</div>}

export function Phase5Flow({onRestartArchive}:{onRestartArchive:()=>void}){const[stage,setStage]=useState<Stage>("transfer");const[index,setIndex]=useState(0);const[selected,setSelected]=useState<string[]>([]);const[checked,setChecked]=useState(false);const[answers,setAnswers]=useState<string[][]>([]);const[review,setReview]=useState(false);const task=stage==="transfer"?transferTasks[index]:finalTestTasks[index];const toggle=(option:string)=>setSelected(items=>task.multipleChoice?(items.includes(option)?items.filter(item=>item!==option):[...items,option]):[option]);const nextTransfer=()=>{if(index===transferTasks.length-1){setIndex(0);setSelected([]);setChecked(false);setStage("transition");return}setIndex(value=>value+1);setSelected([]);setChecked(false)};const nextTest=()=>{const nextAnswers=[...answers,selected];setAnswers(nextAnswers);if(index===finalTestTasks.length-1){setStage("result");return}setIndex(value=>value+1);setSelected([])};const restartTest=()=>{setStage("test");setIndex(0);setSelected([]);setAnswers([]);setReview(false)};
 if(stage==="transition")return <AppShell decorations={decorations}><section className="view view--complete"><p className="eyebrow">Transfer abgeschlossen</p><h1>Bereit für die Abschlussprüfung</h1><p className="completion-copy">Im letzten Abschnitt wenden Sie Ihr Wissen ohne zusätzliche Hilfen an.</p><Button onClick={restartTest}>Abschlussprüfung starten</Button></section></AppShell>;
 if(stage==="result"){const score=scoreTest(answers);const message=score>=7?"Sehr sicher. Die zentralen Grundlagen der Arbeit mit literarischen Texten sitzen.":score>=5?"Gute Grundlage. Einzelne Begriffe oder Textsorten sollten noch einmal wiederholt werden.":"Einige Grundlagen sollten noch einmal angesehen werden. Nutzen Sie das Archiv, um Textsorten, Merkmale und Fachbegriffe erneut zu wiederholen.";return <AppShell decorations={decorations}><section className="view phase5-result"><header className="task-heading"><p className="eyebrow">Abschlussauswertung</p><h1>Das Literatur-Archiv ist erschlossen</h1><p>Sie haben {score} von 8 Aufgaben vollständig richtig gelöst.</p></header><FeedbackBox tone={score>=7?"correct":score>=5?"hint":"neutral"}>{message}</FeedbackBox><Button variant="secondary" onClick={()=>setReview(value=>!value)}>{review?"Lösungen schließen":"Lösungen ansehen"}</Button>{review&&<div className="solution-review">{finalTestTasks.map((item,taskIndex)=>{const correct=isExactAnswer(item,answers[taskIndex]??[]);return <Card key={item.id}><h2>Aufgabe {taskIndex+1}</h2><p>{item.prompt}</p><p><strong>Eigene Antwort:</strong> {answerText(answers[taskIndex]??[])}</p><p><strong>Richtige Antwort:</strong> {answerText(item.correctAnswers)}</p><FeedbackBox tone={correct?"correct":"incorrect"}>{correct?"Richtig":"Noch nicht richtig"}</FeedbackBox></Card>})}</div>}<div className="completion-actions"><Button onClick={onRestartArchive}>Archiv erneut durchlaufen</Button><Button variant="secondary" onClick={restartTest}>Abschlusstest wiederholen</Button></div></section></AppShell>}
 const transfer=stage==="transfer";const exact=transfer&&checked&&isExactAnswer(task,selected);return <AppShell decorations={decorations}><section className="view view--phase3 phase-area"><header className="task-heading"><p className="eyebrow">{transfer?"Transfer":"Abschlussprüfung"} · Aufgabe {index+1} von {transfer?5:8}</p><h1>{transfer?"Wissen verbinden":"Wissen anwenden"}</h1><p>{task.prompt}</p></header><ProgressBar value={index+1} max={transfer?5:8} label={transfer?"Transfer":"Abschlussprüfung"}/><Options task={task} selected={selected} locked={checked} onToggle={toggle}/>{transfer&&!checked&&<div className="actions"><Button disabled={!selected.length} onClick={()=>setChecked(true)}>Auswahl prüfen</Button></div>}{transfer&&checked&&<><FeedbackBox tone={exact?"correct":"incorrect"}>{exact?"Richtig – die Merkmale wurden sinnvoll miteinander verbunden.":"Die Auswahl ist aufgelöst. Richtige, unpassende und fehlende Aussagen sind unten gekennzeichnet."}</FeedbackBox><Card className="transfer-resolution"><p><strong>Richtig ausgewählt:</strong> {answerText(selected.filter(option=>task.correctAnswers.includes(option)))}</p><p><strong>Passte nicht:</strong> {answerText(selected.filter(option=>!task.correctAnswers.includes(option)))}</p><p><strong>Fehlte noch:</strong> {answerText(task.correctAnswers.filter(option=>!selected.includes(option)))}</p></Card><div className="actions"><Button onClick={nextTransfer}>{index===4?"Zur Abschlussprüfung":"Nächste Aufgabe"}</Button></div></>}{!transfer&&<div className="actions"><Button disabled={!selected.length} onClick={nextTest}>{index===7?"Test auswerten":"Nächste Aufgabe"}</Button></div>}</section></AppShell>}
