import { useMemo,useState } from "react";
import { AppShell } from "../../components/AppShell";import { Button } from "../../components/Button";import { Card } from "../../components/Card";import { FeedbackBox } from "../../components/FeedbackBox";import { GlossaryTerm } from "../../components/GlossaryTerm";import { ProgressBar } from "../../components/ProgressBar";
import { communicationTasks,interpretationTasks,isCorrectPhase4Answer,type Phase4Task } from "../../data/phase4";import { shuffle } from "../../utils/shuffle";import { Phase5Flow } from "../phase5/Phase5Flow";
type Stage="arrival"|"communication-model"|"communication-tasks"|"interpretation-model"|"interpretation-tasks"|"summary"|"future";
const decorations=[{asset:"readingWoman",position:"bottom-left",size:"clamp(12rem,22vw,20rem)",opacity:.17,visibility:"tablet-up"},{asset:"bustGlobe",position:"bottom-right",size:"clamp(12rem,22vw,20rem)",opacity:.15,visibility:"desktop"}] as const;
function ChoiceTask<T extends string>({task,index,total,label,onNext}:{task:Phase4Task<T>;index:number;total:number;label:string;onNext:()=>void}){const[selected,setSelected]=useState<T|null>(null);const options=useMemo(()=>shuffle(task.options),[task]);const correct=selected!==null&&isCorrectPhase4Answer(task,selected);return <section className="phase-area"><header className="task-heading"><p className="eyebrow">{label} · Aufgabe {index+1} von {total}</p><h1>Treffen Sie eine Zuordnung</h1></header><ProgressBar value={index+1} max={total} label={label}/><Card className="case-card"><p>{task.prompt}</p><div className="answer-grid phase4-options">{options.map(option=><button className={`answer-option ${selected===option?"answer-option--selected":""}`} key={option} type="button" disabled={selected!==null} onClick={()=>setSelected(option)}>{option}</button>)}</div></Card>{selected&&<><FeedbackBox tone={correct?"correct":"incorrect"}>{correct?task.feedback:<>Richtig ist: <strong>{task.answer}</strong>. {task.feedback}</>}</FeedbackBox><div className="actions"><Button onClick={onNext}>{index===total-1?"Bereich abschließen":"Nächste Aufgabe"}</Button></div></>}</section>}
export function Phase4Flow(){const[stage,setStage]=useState<Stage>("arrival");const[index,setIndex]=useState(0);const advance=(kind:"communication"|"interpretation")=>{const tasks=kind==="communication"?communicationTasks:interpretationTasks;if(index<tasks.length-1){setIndex(value=>value+1)}else{setIndex(0);setStage(kind==="communication"?"interpretation-model":"summary")}};
 if(stage==="arrival")return <AppShell decorations={decorations}><section className="view view--complete"><p className="eyebrow">Vertiefung</p><h1>Transferbereich folgt in Phase 4.</h1><p className="completion-copy">Literarische Kommunikation und Interpretation stehen jetzt im Mittelpunkt.</p><Button onClick={()=>setStage("communication-model")}>Phase 4 beginnen</Button></section></AppShell>;
 if(stage==="future")return <Phase5Flow onRestartArchive={()=>window.location.reload()}/>;
 if(stage==="summary")return <AppShell decorations={decorations}><section className="view phase4-summary"><header className="task-heading"><p className="eyebrow">Phase 4 abgeschlossen</p><h1>Perspektiven erschlossen</h1></header><div className="phase4-summary-grid"><Card><h2>Literarische Kommunikation</h2><p>Realer Autor → Text</p><p>Erzähler → impliziter Leser</p><p>Realer Leser → Deutung</p></Card><Card><h2>Interpretation</h2><p>Text → werkimmanent</p><p>Autor + Entstehungszeit → produktionsorientiert</p><p>Leser + Wirkung → rezeptionsorientiert</p></Card></div><div className="actions"><Button onClick={()=>setStage("future")}>Weiter</Button></div></section></AppShell>;
 if(stage==="communication-tasks")return <AppShell decorations={decorations}><section className="view view--phase3"><ChoiceTask key={index} task={communicationTasks[index]} index={index} total={communicationTasks.length} label="Literarische Kommunikation" onNext={()=>advance("communication")}/></section></AppShell>;
 if(stage==="interpretation-tasks")return <AppShell decorations={decorations}><section className="view view--phase3"><ChoiceTask key={index} task={interpretationTasks[index]} index={index} total={interpretationTasks.length} label="Interpretationsansätze" onNext={()=>advance("interpretation")}/></section></AppShell>;
 if(stage==="communication-model")return <AppShell decorations={decorations}><section className="view view--phase3 phase-area"><header className="task-heading"><p className="eyebrow">Vier Ebenen</p><h1>Literarische Kommunikation</h1><p>Autor und Erzähler sind nicht automatisch identisch. Reale Leser bringen Vorwissen und Erfahrungen ein und können Leerstellen unterschiedlich füllen.</p></header><div className="communication-levels"><Card><span>Ebene 1 · Produktion</span><h2><GlossaryTerm glossaryId="autor">Realer Autor</GlossaryTerm></h2><p>verfasst den literarischen Text</p></Card><Card><span>Ebene 2 · Textinterne Vermittlung</span><h2><GlossaryTerm glossaryId="erzaehler">Erzähler</GlossaryTerm></h2><p>vermittelt innerhalb erzählender Texte das Geschehen</p></Card><Card><span>Ebene 3 · Angelegte Leserrolle</span><h2><GlossaryTerm glossaryId="impliziter-leser">Impliziter Leser</GlossaryTerm></h2><p>ist eine durch den Text vorausgesetzte Leserrolle, keine konkrete Person</p></Card><Card><span>Ebene 4 · Rezeption</span><h2><GlossaryTerm glossaryId="realer-leser">Realer Leser</GlossaryTerm></h2><p>liest, deutet und ergänzt Leerstellen mit eigenen Erfahrungen</p></Card></div><div className="actions"><Button onClick={()=>setStage("communication-tasks")}>Übung beginnen</Button></div></section></AppShell>;
 return <AppShell decorations={decorations}><section className="view view--phase3 phase-area"><header className="task-heading"><p className="eyebrow">Drei Perspektiven</p><h1>Interpretationsansätze</h1></header><div className="interpretation-grid"><Card><h2><GlossaryTerm glossaryId="werkimmanent">Text · werkimmanent</GlossaryTerm></h2><p>Sprache, Aufbau, Figuren, Handlung, Motive, Symbole, Erzählweise und Gesprächsverhalten.</p></Card><Card><h2><GlossaryTerm glossaryId="produktionsorientiert">Autor + Kontext · produktionsorientiert</GlossaryTerm></h2><p>Biografie, Briefe, Epoche, historische Quellen und Entstehungsgeschichte.</p></Card><Card><h2><GlossaryTerm glossaryId="rezeptionsorientiert">Leser + Wirkung · rezeptionsorientiert</GlossaryTerm></h2><p>Historische und heutige Leser, soziale Gruppen, Erfahrungen und Leerstellen.</p></Card></div><Card className="perspective-memory"><strong>Merkhilfe:</strong> Text → werkimmanent · Autor + Entstehungszeit → produktionsorientiert · Leser + Wirkung → rezeptionsorientiert</Card><FeedbackBox tone="hint">Bei der Interpretation literarischer Texte steht zunächst häufig die werkimmanente Analyse im Vordergrund. Biografische, historische oder rezeptionsbezogene Kontexte werden insbesondere dann einbezogen, wenn die Aufgabenstellung dies verlangt oder entsprechende Materialien bereitstellt.</FeedbackBox><div className="actions"><Button onClick={()=>setStage("interpretation-tasks")}>Fälle untersuchen</Button></div></section></AppShell>}
